version: 2

jobs:
  build:
    # working_directory: ~/demo_project

    docker:
      - image: mrpossoms/ubuntu-artful-dev 
        environment:

    steps:
      - checkout

      - run:
          name: Compile collector
          command: make collector

      - run:
          name: Compile predictor 
          command: make predictor

      - run:
          name: Compile actuator 
          command: make actuator

